#### Numpy stands  for numerical Pyhton . is an essential library for scientific computing in python . It provides support for arrays , matrics and a large  collection of high level mathematical function to operate on these data structures.Numpy is central to the python scientific stack underpinning many other libraries such as SciPy , Matplotlib, Pandas, sckit learn, making it a foundational component for numerical computation in Python

In [5]:
import numpy as np
print(dir(np))  # all the functions in nmpy 
len(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

591

##### Q. What is NumPy Array?

- A NumPy array, also known as an ndarray, is the foundation of NumPy. It's a powerful n-dimensional array object designed specifically for storing and manipulating numerical data in Python.
 

In [15]:
# Numpy stores a single type of data if ther is a float in data it will make allthe items as float 
# and if there is a string in the data it will make all the data string 


import numpy as np

r=np.array([1,2,3])
print(r)

r1=np.array([1,2,'3'])
print(r1)  # it made all the items string 

r2=np.array([1,2,3.0])
print(r2) # here it made all the items float 

r3=np.array([1,2.0,3.0])
print(r3)

[1 2 3]
['1' '2' '3']
[1. 2. 3.]
[1. 2. 3.]


In [1]:
# single-dimensional NumPy

import numpy as np

a=np.array([1,2,3])
print(a)
type(a)

# [1 2 3] is not list it is a array cause it do not have commas

# ndaarray means  n-dimensional  array 

[1 2 3]


numpy.ndarray

In [3]:
b=np.array({3,4,5})
print(b)
print(type(b))
b.ndim

{3, 4, 5}
<class 'numpy.ndarray'>


0

In [4]:
b1=np.array({12,13,14})
print(b1.ndim)
print(b1.shape)

0
()


In [8]:
b1=np.array({{12,13,14}})
print(b1.ndim)
print(b1.shape)

TypeError: unhashable type: 'set'

In [6]:
# 2-dimensional Array

c=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c)
print(type(c))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [36]:
# 3-dimensional Array 

d=np.array([[(1,2,3),(4,5,6),(7,8,9)],  [(0,9,8),(5,6,7),(3,5,2)]])

print(d)

print(d.ndim)

print(d.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[0 9 8]
  [5 6 7]
  [3 5 2]]]
3
(2, 3, 3)


In [1]:
# 4-dimensional Array 
import numpy as np

e=np.array([[[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]]])

print(e)

print(e.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4


In [16]:
f=np.array([[[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]]])

print(f)

print(f.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4


In [18]:
g=np.array([[[[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)],[(1,2,3),(4,5,6),(7,8,9)]]]])

print(g)
print(g.ndim)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]

   [[1 2 3]
    [4 5 6]
    [7 8 9]]

   [[1 2 3]
    [4 5 6]
    [7 8 9]]

   [[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5


In [20]:

c=np.array([[[[[[[(1,2,3),(4,5,6),(7,8,9)]]]]]]])
print(c)
print(c.ndim)

[[[[[[[[1 2 3]
       [4 5 6]
       [7 8 9]]]]]]]]
8


In [23]:
a=np.array([[[[[1,2,3]]]]])
print(a)
print(a.ndim)
print(a.shape)

[[[[[1 2 3]]]]]
5
(1, 1, 1, 1, 3)


#### Q. Why do we use NumPy if we alrrady have Pyhton list?

- Python Numpy Array v/s List
- Why Numpy is used in pythonn ? we use pyhton array instead of a list becuase of the below three reasons

     1. Less Memory
     2. Fast
     3.  Convenient

The very first reason to choose NumPy is that it occuples less Memory as compared the list then. it is fast in terms of execution and at the same time , It is very convenient to work with NumPy .So these are the major advantages that pyhton Nimpy array has over list Consider the below example

In [2]:
import numpy as np
import time
import sys

S =range(1000)
print(sys.getsizeof(5)*len(S))

d=np.arange(1000)
print(d.size*d.itemsize)

28000
4000


The above output shows the memory allocated by list (denoted by S) is 28000 whereas the memory allocated by the Numpy is just 4000 from this you can conclude that there is a major difference between the two and this Python Numpy array as the preferred choice over list

Now, let's talk about NumPy array is faster and more convenient whe compared to list 

#### Pyhton NumPy Operations 

- Numpy Array

  You can find the dimension of array, whetherit is a two dimensional array or a single dimensional array 

- ndim

In [38]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])

print(a.ndim)

2


#### itemsize

You  can calculate the bite size of each element. in the below code , here it is defined a single dimensional array and with the help of 'itemsize' function we can find the size of each element 

#### Size

In [3]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a.itemsize)
print(a.ndim)
print(a.shape)
print(a.size)

4
2
(2, 3)
6


In [2]:
import numpy as np 

b1=np.array([[(1,2,3,4),(0,9,8,6)]])

print(b1)
print(b1.ndim)
print(b1.shape)
print('\n')
print(b1.itemsize)
print('\n')

print(b1.size)

[[[1 2 3 4]
  [0 9 8 6]]]
3
(1, 2, 4)


4


8


In [24]:
b1=np.array([(1,2,3,4),(0,9,8,6)])

print(b1)
print(b1.ndim)
print(b1.shape)
print('\n')
print(b1.itemsize)

[[1 2 3 4]
 [0 9 8 6]]
2
(2, 4)


4


In [16]:
b1=np.array([(1,2,3,4),(0,9,8,6),(11,12,13,14,12)])

print(b1)
print(b1.ndim)
print(b1.shape)
print('\n')
print(b1.itemsize)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [17]:
b1=np.array([(1,2,3,4),(0,9,8,6),(11,12,13,14)])

print(b1)
print(b1.ndim)
print(b1.shape)
print('\n')
print(b1.itemsize)


[[ 1  2  3  4]
 [ 0  9  8  6]
 [11 12 13 14]]
2
(3, 4)


4


In [4]:
b1=np.array([[[([1,2,3,0,4]),([0,9,8,6,0]),([12,34,45,23,11]),([1,2,4,6,7])]]])

print(b1)
print(b1.ndim)
print(b1.shape)
print('\n')
print(b1.itemsize)
print(b1.size)

[[[[ 1  2  3  0  4]
   [ 0  9  8  6  0]
   [12 34 45 23 11]
   [ 1  2  4  6  7]]]]
4
(1, 1, 4, 5)


4
20


- Datatype

   You can find the data type of the elements that are stored in an array . so if you want to know the data type of a paticular element , ypu can use 'dtype' function which will print the datatype along with the size. In the below code, we have defined an array where we used the same function 

In [1]:
import numpy as np
a=np.array([(1,2,3)])
print(a.dtype)

int32


In [2]:
a1=np.array(['pawan',12,34,3.4])
a1.dtype

dtype('<U32')

In [10]:
a1=np.array([])  # By default it is float so empty array is also float 
a1.dtype

dtype('float64')

In [9]:
a1=np.array([3.4])
a1.dtype

dtype('float64')

In [3]:
a2=np.array(['pawan'])
a2.dtype

dtype('<U5')

In [15]:
a1=np.array([()])
a1.dtype

dtype('float64')

As you can see the data type of the array is integer 32 bits. similarly, you can find the size and shape of the array using 'size' and               'shape' funtion  respectively 

#### Size
  tells about the total no. of elements in an array 
#### shape
   tells about the number of rows and coloumn 

In [42]:
import numpy as np
a=np.array([(1,2,3,4,5,6,9)])

print(a.size)
print(a.shape)

7
(1, 7)


- reshape

  reshape is  when you change the number of rows and coloumn which gives a new view to an object 

In [45]:
a= np.array([(8,9,10),(11,12,13)])
print(a)
print('\n')
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]


[[ 8  9]
 [10 11]
 [12 13]]


- Sclicing

  this is similar to the the one which is there in the list as well

In [3]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2]) 

# here row(1,2,3,4)mis at index 0 and row (3,4,5,6) is at index 2
# so it is showing the 2nd item at index 0 ie;3

3


In [5]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,3])
print(a[1,2])


4
5


In [4]:
import numpy as np 
x=[1,2,3,5,2,2,2]
y=[2,2,3,6,78,12,12]
z=[89,6,2,45,67,12,33]

paw=np.array([x,y,z])
print(paw)   

paw[1,2]

[[ 1  2  3  5  2  2  2]
 [ 2  2  3  6 78 12 12]
 [89  6  2 45 67 12 33]]


3

In [5]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2]) # calling item ar index 2 from all the rows

[3 5]


Here colon represents all the rows , including zero. Now to get 2nd element , we will call index 2 from both of the rows which gives us the value 3 and 5 respectively 

Next just to remove the condition . let's say we have one more row and don't want to get its 2nd element printed just as the image above. what we can do in such case ? Consider the below code

In [49]:
a=np.array([(8,9),(10,11),(12,13)])
print(a)
print('\n')
print(a[0:2,1])

[[ 8  9]
 [10 11]
 [12 13]]


[ 9 11]


In [53]:
a=np.array([(8,9),(10,11),(12,13)])
print(a)
print('\n')

print(a[0:,1])

[[ 8  9]
 [10 11]
 [12 13]]


[ 9 11 13]


In [54]:
a=np.array([(8,9),(10,11),(12,13)])
print(a)
print('\n')

print(a[:,1])

[[ 8  9]
 [10 11]
 [12 13]]


[ 9 11 13]


#### linspace

  this is another operation in python numpy which returns evenly spaced numbers over a specified interval. Consider the below example
  

In [61]:
a=np.linspace(1,3,3)
print(a)

[1. 2. 3.]


As you can see in the result  , it has printed 3 value between 1 to 3

In [62]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [65]:
a=np.linspace(1,3,2)
print(a)

[1. 3.]


In [7]:
a=np.linspace(1,3)   # by default it will divided into 50 
print(a)

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


- max/min

  Next, we have some more operations in numpy such as to find the minimum, maximum as well the sum of the numpy array. let's go ahead in python numpy tutorial and execute it practically 

In [68]:
a=np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


### Axis in NumPy 

- axis=1 is Row
- axis=0 is coloum

In [14]:
import numpy as np

a=np.array([(1,2,3),(3,4,5)])
print(a)
print(a.sum(axis=0))

[[1 2 3]
 [3 4 5]]
[4 6 8]


In [15]:

a=np.array([(1,2,3),(3,4,5)])
print(a)
print(a.sum(axis=1))

[[1 2 3]
 [3 4 5]]
[ 6 12]


In [12]:

a=np.array([[(1,2,3),(3,4,5)]])
print(a)
print(a.ndim)
print('\n')
print(a.sum(axis=1)) # row
print('\n')
print(a.sum(axis=0)) # column

[[[1 2 3]
  [3 4 5]]]
3


[[4 6 8]]


[[1 2 3]
 [3 4 5]]


In [10]:
a=np.array([[(1,2,3),(3,4,5)]])
print(a)
print(a.ndim)
print('\n')
print(a.sum(axis=1))
print('\n')
print(a.sum(axis=2))

[[[1 2 3]
  [3 4 5]]]
3


[[4 6 8]]


[[ 6 12]]


In [38]:
a=np.array([[[(1,2,3),(3,4,5)],[(6,7,8),(9,10,11)]]])
print(a)
print(a.ndim)
print('\n')
print(a.sum(axis=1))
print('\n')
print(a.sum(axis=0))

[[[[ 1  2  3]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]]
4


[[[ 7  9 11]
  [12 14 16]]]


[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
import numpy as np

a=np.array([(1,2,3,4,5,6)])

print(np.sqrt(a))
print(np.std(a))
print(np.mean(a))
print(np.median(a))
print(np.percentile(a,3))

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]]
1.707825127659933
3.5
3.5
1.15


In [34]:
a=np.array([[(1,2,3),(3,4,5),(1,2,1),(8,7,6)]])

print(np.sqrt(a))

print(np.percentile(a,3))

[[[1.         1.41421356 1.73205081]
  [1.73205081 2.         2.23606798]
  [1.         1.41421356 1.        ]
  [2.82842712 2.64575131 2.44948974]]]
1.0


### Operators 

In [43]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])

print(x+y)

print(x*y)

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


In [9]:
import numpy as np

x1=np.array([[[(1,2,3),(4,5,6)]]])
y1=np.array([[[(1,2,3),(4,5,6)]]])

print(x1+y1)

print(x1*y1)

[[[[ 2  4  6]
   [ 8 10 12]]]]
[[[[ 1  4  9]
   [16 25 36]]]]


#### Ravel 

In [49]:
import numpy as np

x=np.array([(1,2,3),(3,4,5)])

print(x)
print(x.ravel())



[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]


In [59]:
x=np.array([[(1,2,3),(3,4,5)]])

print(x.ndim)

print(x)
y=x.ravel()

print(y)
print(y.ndim)

3
[[[1 2 3]
  [3 4 5]]]
[1 2 3 3 4 5]
1


### Memory control in NumPy

- The bit is the most basic unit of information in computing
- The byte is a unit of infotmation which contains 8 bits

(1byte = 8 bits)

Usinged Integers(often called "unit"s) just like integers (whole numbers) but have the property that they don't have a + or - sign associated with them .Thus they are always non-negative (zero or positive) .We use units when we know the value we are counting will always be non-negative

In [27]:
import numpy as np

a=np.array([(1,2,3),(3,4,5)]) # 32 bytes integers

a.dtype

dtype('int32')

In [28]:
a=np.array([(1,2,3),(3,4,5)],dtype='int8') # changes to less bytes 
a

array([[1, 2, 3],
       [3, 4, 5]], dtype=int8)

In [ ]:
a= np.array([(1,2,3),(3,4,5)],dtype='int8')

#### Byte String

- Byte strings are constrained by the character encoding used. In character encodingf like ASCII, each character is represented by a single       byte,limiting the available characters to the 128 ASCII characters 

- Unicode strings cover a much larger range of characters, including those from various languages and special symbols

- "object" data type  is used for all other data types

- ASCII( American Standard Code for Information Interchange) is a character encoding standard for electronic communication. ASCII codes represent text in computers, telecommunications equipment, and other devices. Because of technical limitations of computer systems at the time it was invented, ASCII has just 128 code points, of which only 95 are printable characters, which severely limited its scope. Modern computer systems have evolved to use Unicode, which has millions of code points, but the first 128 of these are the same as the ASCII set. 
  

- Byte String representation

  bytes/bytes_/S/a

- Unicode strings representation

  U/str/str_/unicode

- Object representation

  object/O

In [30]:
a=np.array([('arvind'),('joshi')])  # string by default is unicode and
                                    # is less than equal to 6
a

array(['arvind', 'joshi'], dtype='<U6')

In [33]:
a=np.array([('arvind'),('joshi')],dtype="<U3")   # changed to <U3
a

array(['arv', 'jos'], dtype='<U3')

In [39]:
a=np.array([('arvind'),('joshi')],dtype="<U0")   # changed to <U3
a

array(['arvind', 'joshi'], dtype='<U6')

In [36]:
# Byte string- ASCII table has 128 characters it limits the data struucture

import numpy as np

a=np.array([('arvind'),('joshi')],dtype="S")
a

array([b'arvind', b'joshi'], dtype='|S6')