In [3]:
 import numpy as np   # np is Elias name 



In [13]:
my_1st=[1,2,3,4,5]

arr=np.array(my_1st)

print(arr)

[1 2 3 4 5]


In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(5,)

In [3]:
import numpy as np
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arre=np.array([my_lst1,my_lst2,my_lst3])

arre

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
arre.shape

# it is showing that the array has 3 Rows and 5 coloumn 

(3, 5)

In [18]:
arre.reshape(5,3) # 5rows , 3 coloumn

# reshape can change the dimensions of the arrays 


array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [19]:
arre.shape # checking after reshaping 

(3, 5)

-  assigning a variable and reshaping 

In [20]:
x=arre.reshape(5,3)
print(x)

print(x.shape) # 5 row 3 column 

[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 9 7]
 [6 8 9]]
(5, 3)


In [21]:
arre.reshape(3,4)  # no. of row and should be in syn with array

ValueError: cannot reshape array of size 15 into shape (3,4)

In [ ]:
arre.reshape(1,1)

In [1]:
arre.reshape(1,15)

NameError: name 'arre' is not defined

### Indexing

In [23]:
## Accessing the array element

arr=np.array(1,2,3,4,5,6,7,8,9)

print(arr[3])

TypeError: array() takes from 1 to 2 positional arguments but 9 were given

In [24]:

arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr[3])

4


#### Row/ column index 

In [25]:
# for 2-d array
print(arre)
print(arre.ndim)
print(arre[3]) # row index 3 is not persent 

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
2


IndexError: index 3 is out of bounds for axis 0 with size 3

- in this [1,2,3,4,5] is row index=0
          [2,3,4,5,6] is row index =1
          [9,7,6,8,9] is row index=2
- similarly 
           1  2  3  
           2  3  4
           9  7  6
     are coloumn index=0
           ''     ''  =1
           ''     '' = 2

In [5]:
import numpy as np 
x=[1,2,3,5,2,2,2,]
y=[2,2,3,6,78,12,12]
z=[89,6,2,45,67,12,33]

paw=np.array([x,y,z])
print(paw)   

paw[1] # it is giving the row index 1 ie;[2,2,3,6,78,12,12]

[[ 1  2  3  5  2  2  2]
 [ 2  2  3  6 78 12 12]
 [89  6  2 45 67 12 33]]


array([ 2,  2,  3,  6, 78, 12, 12])

### Slicing 

In [26]:
arre[:,:] # : on left means all the row 
        # : on right means all the colomn

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [27]:
arre[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [28]:
# if i want only 1 , 2
#               2 , 3  of the arrray

arre[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [29]:
arre[1:2,3:4]

array([[5]])

In [30]:
arre[1:,3:]

array([[5, 6],
       [8, 9]])

In [31]:
arre

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [32]:
arre[1:2,:]

array([[2, 3, 4, 5, 6]])

In [33]:
arre[1:,2:4]

array([[4, 5],
       [6, 8]])

In [34]:
arre[2:,1:2]

array([[7]])

In [35]:
arre[0:,1:2]

array([[2],
       [3],
       [7]])

In [36]:
arre

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [37]:
arre[0:1,1:3]

array([[2, 3]])

In [38]:
arre[1:2,2:4]

array([[4, 5]])

In [39]:
print(arre[2,4])
type(arre[2,4])

9


numpy.int32

In [40]:
print(arre[2:,4:])
type(arre[2:,4:])

[[9]]


numpy.ndarray

In [41]:
arre[1:2,1:4]

array([[3, 4, 5]])

In [9]:
import numpy as np

S=np.array([1,2,3,4,5,6,7,8,9,0])

print(S[0])
print(S[1])
print(S[2])

S[0:1,3:4]

1
2
3


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### Arrange

In [42]:
arre

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [43]:
print(arre=np.arange(0,10))

TypeError: 'arre' is an invalid keyword argument for print()

In [44]:
arre=np.arange(0,10) # values b/w 0(start) to 10(end)

arre

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arre=np.arange(3,6) 

arre

array([3, 4, 5])

In [46]:
arre=np.arange(0,10,step=2)  # 2 is step 
arre

array([0, 2, 4, 6, 8])

### Linspace

In [47]:
arr1=np.array([my_lst1,my_lst2,my_lst3])

arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [48]:
arr1=np.linspace(0,10,50)  # from 0 to 10 we neec 50 numbers/ points (these are equally spaced points)

arr1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### Copy function and Broadcasting 

In [99]:
r=np.array([0, 2, 4, 6, 8])
r

array([0, 2, 4, 6, 8])

In [100]:
r[3:]=100 # it says from the 3rd index replace all the indexes with 100
r

array([  0,   2,   4, 100, 100])

In [101]:
r3=np.array([[[(1,2,3),(4,5,6),(7,8,9)]]])

print(r3.ndim)
print(r3)

4
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [102]:
r3[2:]=100
r3

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [103]:
r3[0:]=100
r3

array([[[[100, 100, 100],
         [100, 100, 100],
         [100, 100, 100]]]])

### Copy

In [104]:
# Refrencing / reference type/ Deep Copy 
ar=r
r

array([  0,   2,   4, 100, 100])

In [105]:
ar[2:]=500
print(ar)
print(r) # changing ar also changed the items of r this is referencing 

[  0   2 500 500 500]
[  0   2 500 500 500]


In [118]:
# .Copy() - it creates another memory storage for the new array
print(r)
arr4=r.copy()



[  0   2 500 500 500]


In [119]:
arr4

array([  0,   2, 500, 500, 500])

In [123]:
arr4[2:]=0 # it doesn't changed the r array cause its .copy()
print(arr4)
print(r)  

[0 2 0 0 0]
[  0   2 500 500 500]


#### Important conditions usefull in Exploratory Data Analysis 

In [3]:
import numpy as np

X=np.array([12,34,53,1,2,2,45,64,21,78])

In [4]:
val=2

X<2

array([False, False, False,  True, False, False, False, False, False,
       False])

In [5]:
X*2

array([ 24,  68, 106,   2,   4,   4,  90, 128,  42, 156])

In [6]:
X>+30

array([False,  True,  True, False, False, False,  True,  True, False,
        True])

In [7]:
X

array([12, 34, 53,  1,  2,  2, 45, 64, 21, 78])

In [10]:
# If we want to get the condition printed 

X[X<40]

array([12, 34,  1,  2,  2, 21])

#### Arange and reshape together (Create and reshaping array)

In [26]:
Y=np.arange(0,20)
Y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
y=np.arange(0,20).reshape(5,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Ones (replace arrays by one))

In [36]:
y=np.ones(20) # here by defualt the dtype is float 
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [41]:
np.ones((6,4),dtype=int) # here we gave the dtype as integers 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Random Distribution

   all the elements of random sampling will selected b/w 0 to 1

In [45]:
np.random.rand(3) # 1-D

array([0.54311099, 0.6298674 , 0.91063378])

In [46]:
np.random.rand(3,3) # 2-D

array([[0.00624036, 0.93608061, 0.20427211],
       [0.45521654, 0.02171359, 0.82597595],
       [0.68657239, 0.93301331, 0.98806099]])

### Randn 

 ( it will selection the samples from thre "Standard Normal" distribution)

In [47]:
np.random.randn(2)

array([ 0.59236327, -0.45311856])

In [50]:
arr_r=np.random.randn(4,4)

arr_r

array([[ 0.26031941,  0.03061856, -0.78820009,  0.59988969],
       [-0.62527331, -0.06789886, -0.6400095 , -0.08697016],
       [ 1.79458256,  0.99475443, -2.15859824,  1.07487339],
       [ 0.36563561,  1.18086334, -1.47494576, -3.17938582]])

### Astype(int)

used to convert an integer data to a different type

In [6]:
import numpy as np 

a=[30,40,20,40,30]
x1=np.array(a)
print(x1)
print(x1.shape)

print(x1.astype(float))
print(x1.astype(str))

[30 40 20 40 30]
(5,)
[30. 40. 20. 40. 30.]
['30' '40' '20' '40' '30']


In [9]:
a1=np.array(['1','2','3','4','5'])

print(a1)
print(a1.astype(int))

['1' '2' '3' '4' '5']
[1 2 3 4 5]


In [12]:
b1=np.array(['hello'])
print(b1)

print(b1.astype(int)) # can't change alphabatic string into integer abd vice-versa

['hello']


ValueError: invalid literal for int() with base 10: 'hello'

In [14]:
import numpy as np 

a=[30,40,20,40,30]
x1=np.array(a)
print(x1)

print(x1.dtype) # datatype of array 
print(type(x1)) # datatype of variable 

[30 40 20 40 30]
int32
<class 'numpy.ndarray'>


## Mathematical operations 

We can use symbols  as well as methods for operations 

- g=a-b / np.subtract(a,b)

- b+a / p.add(a,n)

- a/b / np.divide(a,b)

- a*b / np.multiply(a,b)

- np.exp()

- np.sqrt()

- np.power()


In [17]:
import numpy as np

arr=np.array([30,40,60,20,10])
arr1=np.array([30,40,60,10,3])

print(np.add(arr,arr1))
print(arr+arr1)

[ 60  80 120  30  13]
[ 60  80 120  30  13]


In [20]:
arr=np.array([[30,40,60],[60,20,10]])
arr1=np.array([[30,40,60],[15,10,3]])

print(np.subtract(arr,arr1))

[[ 0  0  0]
 [45 10  7]]


- Power()

In [22]:
arr=np.array([3,4,6,2,1])
arr1=np.array([3])

print(np.power(arr,arr1))  # elements of arr have power 3 which is element of arr1


[ 27  64 216   8   1]


In [23]:
arr=np.array([3,4,6,2,1])
arr1=np.array([3,2])
print(np.power(arr,arr1))

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [25]:
arr=np.array([3,4,6,2,1])
arr1=np.array([3,2,3,2,3])
print(np.power(arr,arr1))

[ 27  16 216   4   1]


### Combining and Spliting Arrays

In [8]:
# Concatenate
import numpy as np
arr1=np.array([30,40,50])
arr2=np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [6]:
import numpy as np

p=np.array([[30,40,50]])
p1=np.array([[5,5,3]])

print(np.concatenate([p,p1],axis=1))

print(np.concatenate([p,p1],axis=0))

[[30 40 50  5  5  3]]
[[30 40 50]
 [ 5  5  3]]


In [11]:
c=np.array([[(30,40,50),(20,60,40),(80,90,70)]])
c1=np.array([[(5,5,3),(9,6,3),(2,3,7),(6,7,3)]])

print(c)
c1

[[[30 40 50]
  [20 60 40]
  [80 90 70]]]


array([[[5, 5, 3],
        [9, 6, 3],
        [2, 3, 7],
        [6, 7, 3]]])

In [13]:
print(np.concatenate([c,c1])) # c/z no. of row and coloumn in c and c1 is not same so will not concatenate 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [14]:
c=np.array([[(30,40,50),(20,60,40),(80,90,70),(30,20,10)]])
c1=np.array([[(5,5,3),(9,6,3),(2,3,7),(6,7,3)]])

print(c)
c1

[[[30 40 50]
  [20 60 40]
  [80 90 70]
  [30 20 10]]]


array([[[5, 5, 3],
        [9, 6, 3],
        [2, 3, 7],
        [6, 7, 3]]])

In [18]:
print(np.concatenate([c,c1],axis=0))

[[[30 40 50]
  [20 60 40]
  [80 90 70]
  [30 20 10]]

 [[ 5  5  3]
  [ 9  6  3]
  [ 2  3  7]
  [ 6  7  3]]]


In [19]:
print(np.concatenate([c,c1],axis=1))

[[[30 40 50]
  [20 60 40]
  [80 90 70]
  [30 20 10]
  [ 5  5  3]
  [ 9  6  3]
  [ 2  3  7]
  [ 6  7  3]]]


In [20]:
print(np.concatenate([c,c1]))

[[[30 40 50]
  [20 60 40]
  [80 90 70]
  [30 20 10]]

 [[ 5  5  3]
  [ 9  6  3]
  [ 2  3  7]
  [ 6  7  3]]]


In [22]:
# horizontal concatenation  or we can use axis=1
print(np.hstack([c,c1]))

[[[30 40 50]
  [20 60 40]
  [80 90 70]
  [30 20 10]
  [ 5  5  3]
  [ 9  6  3]
  [ 2  3  7]
  [ 6  7  3]]]


In [23]:
# Vertical concatenation  or we can use axis=0

print(np.vstack([c,c1]))

[[[30 40 50]
  [20 60 40]
  [80 90 70]
  [30 20 10]]

 [[ 5  5  3]
  [ 9  6  3]
  [ 2  3  7]
  [ 6  7  3]]]


### Spliting 

In [28]:
e=np.array([20,40,30,40,10,20])

print(np.array_split(e,3))

# it splited array into three parts 

[array([20, 40]), array([30, 40]), array([10, 20])]


In [26]:
f=np.array([20,40,30,40,10,20,90])

print(np.array_split(f,3))

[array([20, 40, 30]), array([40, 10]), array([20, 90])]


In [27]:
f=np.array([20,40,30,40,10,20,90])

print(np.array_split(f,0.5))

ValueError: number sections must be larger than 0.

In [41]:
e=np.array([20,40,30,40,10,20])

b=np.array_split(e,3)
print(b)
# now indexing b

print(b[1])
b[0]

[array([20, 40]), array([30, 40]), array([10, 20])]
[30 40]


array([20, 40])

In [45]:
# for n-d array 

D=np.array([[[(1,2,3),(4,5,6),(7,8,9)]]])
D

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [50]:
print(np.array_split(D,3))

[array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]]), array([], shape=(0, 1, 3, 3), dtype=int32), array([], shape=(0, 1, 3, 3), dtype=int32)]


In [53]:

D=np.array([[1,2,3,4],[6,7,8,9]])
print(D)
print(np.array_split(D,3))

[[1 2 3 4]
 [6 7 8 9]]
[array([[1, 2, 3, 4]]), array([[6, 7, 8, 9]]), array([], shape=(0, 4), dtype=int32)]


## Adding and Removing Elements in the Arrays

#### functions

 - np.append (h,g)
 - np.insert (a,1,5)
 - np.delete (a,[1])

### Append

In [54]:
import numpy as np

a=np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [55]:
a1=np.array([[20,40,60,80]])

print(np.append(a1,90))

[20 40 60 80 90]


In [8]:
# for n-d arrays 
import numpy as np
a2=np.array([[(10,20),(30,40)]])
print(a2)

np.append(a2,50)

# it will convert the n-d array into 1-d array so we have to insert elements instead of append 

[[[10 20]
  [30 40]]]


array([10, 20, 30, 40, 50])

### Insert 

In [11]:
# insert  for 1-d array 

np.insert(a2,1,60)

array([10, 60, 20, 30, 40])

In [17]:
a3=np.array([[(1,2,3),(4,5,6)]])
print(a3)

np.insert(a3,1,30) # it made the array 1-d 

[[[1 2 3]
  [4 5 6]]]


array([ 1, 30,  2,  3,  4,  5,  6])

In [21]:
a3=np.array([[(1,2,3),(4,5,6)]])
print(a3)

np.insert(a3,1,[50,60],axis=1)

[[[1 2 3]
  [4 5 6]]]


ValueError: could not broadcast input array from shape (1,1,2) into shape (1,1,3)

In [23]:
a3=np.array([[(1,2,3),(4,5,6)]])
print(a3)

np.insert(a3,1,[50,60,70],axis=1)

[[[1 2 3]
  [4 5 6]]]


array([[[ 1,  2,  3],
        [50, 60, 70],
        [ 4,  5,  6]]])

In [24]:
a3=np.array([[(1,2,3),(4,5,6)]])
print(a3)

np.insert(a3,0,[50,60,70],axis=1)

[[[1 2 3]
  [4 5 6]]]


array([[[50, 60, 70],
        [ 1,  2,  3],
        [ 4,  5,  6]]])

In [27]:
a3=np.array([[(1,2,3),(4,5,6)]])
print(a3)

np.insert(a3,1,[50,60,70],axis=0)

[[[1 2 3]
  [4 5 6]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[50, 60, 70],
        [50, 60, 70]]])

In [33]:
a3=np.array([[(1,2,3),(4,5,6)]])
print(a3)

np.insert(a3,0,[50,60,70],axis=0)

[[[1 2 3]
  [4 5 6]]]


array([[[50, 60, 70],
        [50, 60, 70]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

### Delete 

In [43]:
a2=np.array([[20,40],[50,50],[60,80],[50,50]])
a2

array([[20, 40],
       [50, 50],
       [60, 80],
       [50, 50]])

In [44]:
np.delete(a2,1,axis=0)

array([[20, 40],
       [60, 80],
       [50, 50]])

In [45]:
np.delete(a2,0,axis=1)

array([[40],
       [50],
       [80],
       [50]])

In [49]:
a2

np.delete(a2,3,axis=0)

array([[20, 40],
       [50, 50],
       [60, 80]])

## Search, Sort and Filter Arrays 

### Sort 

In [50]:
import numpy as np

b1=np.array([2,31,6,3,4,3,643,2,55,68,2])

np.sort(b1)

array([  2,   2,   2,   3,   3,   4,   6,  31,  55,  68, 643])

In [51]:
b1=np.array([[2,31,6,3,4,],[3,2,55,68,2]])

np.sort(b1)

array([[ 2,  3,  4,  6, 31],
       [ 2,  2,  3, 55, 68]])

### Search

In [54]:
b2=np.array([3,4,1,7,8])

np.where(b2==4)



(array([1], dtype=int64),)

In [57]:
np.where(b2%2==0)

(array([1, 4], dtype=int64),)

In [62]:
# for n-d array
print(b1)

print(np.where(b1%2==0))

[[ 2 31  6  3  4]
 [ 3  2 55 68  2]]
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 2, 4, 1, 3, 4], dtype=int64))


In [65]:
#search sorted 

ar=np.array([1,2,3,4,5,6,7,8]) # values must be sorted 

np.searchsorted(ar,2)

1

### Filter

- Creating New array by existing array 

In [67]:
import numpy as np

ar=np.array([20,30,40,50])

fa=[True,False,True,False] 

new=ar[fa]
print(new)

[20 40]


In [69]:
fa=ar>35

new1=ar[fa]

print(new1)

[40 50]


In [71]:
x=ar%3==0

new2=ar[x] 

print(new2)

[30]


### Aggeregating Function In Arrays 

In [9]:
import numpy as np 

a=np.array([20,40,60,70])

print(np.sum(a))
print(np.min(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))  # cummilative sum 
print(np.cumprod(a)) # cummilative product

190
20
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [10]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]

price=np.array(a)

quantity=np.array(b)

print(price,'\n', quantity)

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]


In [11]:
print(np.sum(price))

1029


In [19]:
c=np.cumprod([price,quantity],axis=0)
print(c)

print(np.sum(c[1])) # sum of row index 1 
print(c[1].sum()) # another way 

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
31270
31270


## Statistical Function in Arrays 

In [29]:
import numpy as np 
baked_food=[200,300,150,130,200,280,170,188]
a=np.array(baked_food)

print(np.mean(baked_food))
print(np.median(baked_food))
print(np.mode(baked_food)) # numpy do not have function mode 

202.25
194.0


AttributeError: module 'numpy' has no attribute 'mode'

In [38]:
import statistics as stats

print(stats.mode(baked_food))

print(np.std(baked_food)) # standard deviation 
print(np.var(baked_food)) # variance= std**2


200
55.68157235567257
3100.4375


In [42]:
# corelation coffecient 

tobacco_con=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]

print(np.corrcoef([tobacco_con,deaths]))

# -1 represent inversely proportional relationsip
# 1 represents proportional relationship
# 0 means no relationship 

[[1.         0.99015454]
 [0.99015454 1.        ]]
