In [1]:
import numpy as np
import pandas as pd 


In [2]:
data={"State":['UK','UP','HP','Punjab','haryana','MP'],"Year":[2000,2001,2002,2003,2004,2006],
       "population":[1.5,3.5,3.2,5.6,2.1,1.3]}

pd.DataFrame(data)

State  Year  population
0       UK  2000         1.5
1       UP  2001         3.5
2       HP  2002         3.2
3   Punjab  2003         5.6
4  haryana  2004         2.1
5       MP  2006         1.3

### Head() / Tail()

In [3]:
d0=pd.DataFrame({'State':['UK','UP','HP','Punjab','haryana','MP'],"Year":[2000,2001,2002,2003,2004,2006],
          "population":[1.5,3.5,3.2,5.6,2.1,1.3]})

In [4]:
d0

State  Year  population
0       UK  2000         1.5
1       UP  2001         3.5
2       HP  2002         3.2
3   Punjab  2003         5.6
4  haryana  2004         2.1
5       MP  2006         1.3

In [5]:
d0.head(2)

State  Year  population
0    UK  2000         1.5
1    UP  2001         3.5

In [6]:
d0.tail(2)

State  Year  population
4  haryana  2004         2.1
5       MP  2006         1.3

In [7]:
# If you specify a sequence of the columns, the DataFrame's column will be arranged in that order

D1=pd.DataFrame(data, columns=["year","state","population"])
D1

year state  population
0  NaN   NaN         1.5
1  NaN   NaN         3.5
2  NaN   NaN         3.2
3  NaN   NaN         5.6
4  NaN   NaN         2.1
5  NaN   NaN         1.3

In [8]:
pd.DataFrame(data, columns=["state", "year", "population"])

state year  population
0   NaN  NaN         1.5
1   NaN  NaN         3.5
2   NaN  NaN         3.2
3   NaN  NaN         5.6
4   NaN  NaN         2.1
5   NaN  NaN         1.3

In [9]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [10]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [11]:
frame1=pd.DataFrame(data, columns=["pop", "state", "year"])

frame1

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [12]:
frame1.columns

Index(['pop', 'state', 'year'], dtype='object')

In [13]:
Cdata=pd.DataFrame([["Name",["pawan","Gomas","neeraj"]],["class",[1,2,3]],["weight",[50,40,80]]])

Cdata

0                       1
0    Name  [pawan, Gomas, neeraj]
1   class               [1, 2, 3]
2  weight            [50, 40, 80]

In [14]:
Ddata=pd.DataFrame([["Name","pawan","Gomas","neeraj"],["class",1,2,3],["weight",50,40,8]])

Ddata

0      1      2       3
0    Name  pawan  Gomas  neeraj
1   class      1      2       3
2  weight     50     40       8

In [15]:
Ddata=pd.DataFrame([["pawan","Gomas","neeraj"],[1,2,3],[50,40,8]],columns="NAME","CLASS","WEIGHT")

Ddata

SyntaxError: positional argument follows keyword argument (2466250415.py, line 1)

In [16]:
Ddata=pd.DataFrame([["pawan","Gomas","neeraj"],[1,2,3],[50,40,8]],columns=["NAME","CLASS","WEIGHT"])

Ddata

NAME  CLASS  WEIGHT
0  pawan  Gomas  neeraj
1      1      2       3
2     50     40       8

In [17]:
Ddata=pd.DataFrame([["pawan","Gomas","neeraj"],[1,2,3],[50,40,8]],columns=["NAME","CLASS","WEIGHT"],index=[1,2,3])

Ddata

NAME  CLASS  WEIGHT
1  pawan  Gomas  neeraj
2      1      2       3
3     50     40       8

In [18]:
Ddata=pd.DataFrame([["pawan",12,78],["Gomas",11,90],["Neeraj",14,80]],columns=["NAME","CLASS","WEIGHT"],index=[1,2,3])

Ddata

NAME  CLASS  WEIGHT
1   pawan     12      78
2   Gomas     11      90
3  Neeraj     14      80

In [19]:
Ddata.columns

Index(['NAME', 'CLASS', 'WEIGHT'], dtype='object')

In [20]:
Ddata.index

Index([1, 2, 3], dtype='int64')

In [21]:
Ddata["NAME"]

1     pawan
2     Gomas
3    Neeraj
Name: NAME, dtype: object

In [22]:
pd.DataFrame(Ddata,columns=["NAME","CLASS","WEIGHT","SUBJECT"])

NAME  CLASS  WEIGHT  SUBJECT
1   pawan     12      78      NaN
2   Gomas     11      90      NaN
3  Neeraj     14      80      NaN

In [23]:
Ddata["SUBJECT"]=["Math","English","Hindi"]

Ddata

NAME  CLASS  WEIGHT  SUBJECT
1   pawan     12      78     Math
2   Gomas     11      90  English
3  Neeraj     14      80    Hindi

In [24]:
pd.DataFrame(Ddata,index=[1,2,3,4])

# now for adding data in row 4 we have to edit the columns 

NAME  CLASS  WEIGHT  SUBJECT
1   pawan   12.0    78.0     Math
2   Gomas   11.0    90.0  English
3  Neeraj   14.0    80.0    Hindi
4     NaN    NaN     NaN      NaN

In [25]:
pd.DataFrame(Ddata,pd.Index([1,2,3,4,5]))

NAME  CLASS  WEIGHT  SUBJECT
1   pawan   12.0    78.0     Math
2   Gomas   11.0    90.0  English
3  Neeraj   14.0    80.0    Hindi
4     NaN    NaN     NaN      NaN
5     NaN    NaN     NaN      NaN

In [26]:
# If you pass a column that isn't contained in the dictionary, it will appear with missing values in the result

frame2=pd.DataFrame(data,columns=["year","state","pop","debt"])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [27]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

- A column in a dataFrame cab be retrieved as a series either by dictionary-like notation or by using the dot attribute notation 

In [28]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [29]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

 ##### Note  

 - frame2[column] works for any column name, but frame2.column works only when the column name is valid Pyhton variable

### .loc() and .iloc()

In [30]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [31]:
frame2.loc[1] # giving the detail of row index 1

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [32]:
frame2.loc[0]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: 0, dtype: object

In [33]:
frame2.iloc[1:3,0:] # by .iloc we can slice the row and index 

year state  pop debt
1  2001  Ohio  1.7  NaN
2  2002  Ohio  3.6  NaN

- Columns can be modified by assignment. For example, the empty debt column could be assigned a scalar value or an array of values 

In [34]:
frame2["debt"]=16.5

In [35]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [36]:
frame2["debt"]=np.arange(0,6)
frame2

year   state  pop  debt
0  2000    Ohio  1.5     0
1  2001    Ohio  1.7     1
2  2002    Ohio  3.6     2
3  2001  Nevada  2.4     3
4  2002  Nevada  2.9     4
5  2003  Nevada  3.2     5

#### Series()

- When you are assigning lists or arrrays to a column, the value lenght must match the lenght of dataframe. If you are assigning a series, its lable will be realigned exactly to the Dataframe's index, inserrting missing values in any index values not present 

In [37]:
val =pd.Series([-1.2,-1.5,-1.7], index=[2,4,5])

frame2["debt"]=val

frame2 

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

- Assigning a column that doesn't exist will create a new column.
- the del keyword will delete columns like with a ditionary. As an example. I first add a new column of boolean value where the state column equals "ohio"

In [38]:
frame2["eastern"]=frame2["state"]== "Ohio"
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

- New frame cann't be created by frame2.eastern (dot attribution notation)

#### del []

In [39]:
# the del method can then be used to remove this column

del frame2["eastern"]

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

- The column returned from indexing a DataFrame is a view on the underlying data, not a copy. Thus, any in-place modifications to the Series will be reflected in the DataFrame. The column can be explicitly copied with the Series’s copy method.


In [40]:
# Another common form of data is a nested dictionary of dictionaries:

population={"Ohio":{2000:1.5,2001:1.7,2002:3.6},"Nevada":{2001:2.4,2002:2.9}}

frame3=pd.DataFrame(population)

frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

 - if the nested dictionary is passed to the dataframe, pandas will interpret the outer dictionary keys as the columns, and the inner keys as the Row indices

#### Transpose

In [41]:
# you can transpose the DataFrame (swap rows and columns)
# with similar syntax to a numpy array:

frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

- Note that transposing discards the column data types if the columns do not all have the same data type, so transposing and then transposing back may lose the previous type information. The columns become arrays of pure Python objects in this case.


The keys in the inner dictionaries are combined to form the index in the result. This isn’t true if an explicit index is specified:

In [42]:
pd.DataFrame(population, index=[2001,2002,2003]) # index is specified 

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [43]:
# Dictionaries  of Series are treated in much the same way:

pdata={"Ohio":frame3["Ohio"][:-1],
      "Nevada":frame3["Nevada"][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

- If Data frame's index and column have their name attributes set, these will also be displayed:
  

In [44]:
frame3.index.name= "year"
frame3.columns.name= "state"

frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

- If the DataFrame's columns are different data types, the data type of the returned array will be chosen to accommodate all of the columns 

In [45]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

## Index Objects 

  - Pandas' Index objects are responsible for holding the axis labels (including a DataFrame's column names) and other metadata (like the axis name or names)

  - Any array or other sequence of lables you use when constructing a series or dataframe is internally converted to an index 

In [46]:
import pandas as pd 
import numpy as np 

obj=pd.Series(np.arange(3), index=["a","b","c"])

obj

a    0
b    1
c    2
dtype: int32

In [47]:
ind=obj.index
ind

Index(['a', 'b', 'c'], dtype='object')

In [48]:
ind[1:]

Index(['b', 'c'], dtype='object')

-  Index objects are immtable and thus can't be modified by user.

In [49]:
ind[1]="d" # typeError: Index does not support mutable operations


TypeError: Index does not support mutable operations

In [50]:
# Immutability makes it safer to share Index object among data structures:

labels= pd.Index(np.arange(3))

print(labels)

obj2=pd.Series([1.5,-2.5,0],index=labels)

obj2.index is labels 

obj2

Index([0, 1, 2], dtype='int32')


0    1.5
1   -2.5
2    0.0
dtype: float64

In [51]:
H=pd.Series(np.arange(4))
H

0    0
1    1
2    2
3    3
dtype: int32

In [52]:
G=pd.Series(np.arange(-5,-1),index=H)
G

0   -5
1   -4
2   -3
3   -2
dtype: int32

In [53]:
# Ind addition to being array-like, an Index also behaves like a fixed- size set:

populations={"Ohio":{2000:1.5,2001:1.7,2002:3.6},
              "Nevada":{2001:2.4,2002:2.9}}

frame3= pd.DataFrame(populations)

print(frame3)
print(frame3.index)
print(frame3.columns)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
Index([2000, 2001, 2002], dtype='int64')
Index(['Ohio', 'Nevada'], dtype='object')


In [54]:
print("Ohio" in frame3.columns)
print(2003 in frame3.index)

True
False


In [55]:
# Unlike Python sets a pandas Index can contain duplicates labels but are immutable :

pd.Index(["foo","foo","bar","bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Pandas SERIES



  -  pandas contains data structures and data manipulation tools designed to make data cleaning and analysis fast and convenient in Python.

- pandas is often used in tandem with numerical computing tools like NumPy and SciPy, analytical libraries like statsmodels and scikit-learn, and data visualization libraries like matplotlib.

 -   . pandas adopts significant parts of NumPy's idiomatic style of array-based computing, especially array-based functions and a preference for data processing without for loops.

-    While pandas adopts many coding idioms from NumPy, the biggest difference is that pandas is designed for working with tabular or heterogeneous data. NumPy, by contrast, is best suited for working with homogeneously typed numerical array data.



In [56]:
import numpy as np
import pandas as pd

In [57]:
# import series and DataFrame into the local namespace 
# Since they are so frequently used 

from pandas import Series , DataFrame 

#### Introduction to pandas Data structures 

- To get started with pandas, you will need to get comfortable with its two workhorse data structures: Series and DataFrame. While they are not universal solution for every problem, they provide a solid foundation for a wide range of data tasks.

##### Series

- A series is a one-dimensional array-like object containing a sequence of values(of similar types to NumPy types) of the same type and an associated array of data labels, called its index. The simplest Series is formed from only an array of data 

In [58]:
obj=pd.Series(4,7,-5,3) # error because no []

TypeError: Index(...) must be called with a collection of some kind, 7 was passed

In [106]:
obj=pd.Series([4,7,-5,3])

obj

0    4
1    7
2   -5
3    3
dtype: int64

The string representation of a Series displayed interactively shows the index on the left and the values on the right. Since we did not specify an index for the data, a default one consisting of the integers 0 through N - 1 (where N is the length of the data) is created. You can get the array representation and index object of the Series via its array and index attributes, respectively:


In [60]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [61]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [62]:
 # Creatin a Series with an index identifying each data point with a label

obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])

print(obj2)

obj2.index

d    4
b    7
a   -5
c    3
dtype: int64


Index(['d', 'b', 'a', 'c'], dtype='object')

Compared with Numpy arrays, you can use labels in the index when selecting single values or a set of values  

In [63]:
obj2['a']

-5

In [64]:
obj2['b']='pawan'

C:\Users\hplap\AppData\Local\Temp\ipykernel_13648\2166056057.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'pawan' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  obj2['b']='pawan'


In [71]:
obj2['b']=789

obj2

d      4
b    789
a     -5
c      3
dtype: object

In [72]:
obj2[['c','a','d']]

# Here ['c','a','d'] is interpreted as a list of indices, even though it contains string instead of integers

c     3
a    -5
d     4
dtype: object

- Using NumPy functions or NumPy-like operations, such as filtering with a Boolean array, scalar multiplication, or applying math functions, will preserve the index-value link:

In [73]:
obj2[obj2>0]

d      4
b    789
c      3
dtype: object

In [74]:
obj2*2

d       8
b    1578
a     -10
c       6
dtype: object

In [75]:
obj2[obj2>0]

obj2*2


d       8
b    1578
a     -10
c       6
dtype: object

In [76]:
obj2[obj2 > 0]


obj2*2


import numpy as np

np.exp(obj2)

TypeError: loop of ufunc does not support argument 0 of type int which has no callable exp method

Another way to think about a Series is  as a fixed- lenght, ordered dictonary, as it is a mapping of index caalues to data values. It can be used in many cintxt when you might use a dictionary 

In [ ]:
'b' in obj2

 - If you have data contained in a python dictionary, you can create a series from it by passing the dictionary 

In [77]:
sdata={"Ohio":35000,"Texas":71000,"Oregon":16000,"Utah":5000}

In [78]:
obj3=pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [79]:
# A series can be converted back to dictionary with its to_dict ,method

obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [80]:
states=["clifornia","Ohio","Texas","Oregon"]

pd.Series(obj3,index=states)

clifornia        NaN
Ohio         35000.0
Texas        71000.0
Oregon       16000.0
dtype: float64

Here, three values found in sdata were placed in the appropriate locations, but since no value for "California" was found, it appears as NaN (Not a Number), which is considered in pandas to mark missing or NA values. Since "Utah" was not included in states, it is excluded from the resulting object

In [81]:
L=[["pawan","Himani","sumit"],[200,300,400]]

In [82]:
Ldata=pd.Series(L)
Ldata

0    [pawan, Himani, sumit]
1           [200, 300, 400]
dtype: object

In [83]:
Ldata.to_list()

[['pawan', 'Himani', 'sumit'], [200, 300, 400]]

- I will use the terms “missing,” “NA,” or “null” interchangeably to refer to missing data. The isna and notna functions in pandas should be used to detect missing data:


In [84]:
obj4=pd.Series(sdata)
print(obj4)

ind=["Ohio","Texas","california","Oregon","Utah","amsterdam"]

obj5=pd.Series(obj4,index=ind)

obj5

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


Ohio          35000.0
Texas         71000.0
california        NaN
Oregon        16000.0
Utah           5000.0
amsterdam         NaN
dtype: float64

- Checking for empty/ null indexs

In [85]:
pd.isna(obj5)  # 

Ohio          False
Texas         False
california     True
Oregon        False
Utah          False
amsterdam      True
dtype: bool

In [86]:
pd.isnull(obj5)

Ohio          False
Texas         False
california     True
Oregon        False
Utah          False
amsterdam      True
dtype: bool

In [87]:
pd.notna(obj5)

Ohio           True
Texas          True
california    False
Oregon         True
Utah           True
amsterdam     False
dtype: bool

In [88]:
# another way of writing 

print(obj5.isna())
print(obj5.notna())

Ohio          False
Texas         False
california     True
Oregon        False
Utah          False
amsterdam      True
dtype: bool
Ohio           True
Texas          True
california    False
Oregon         True
Utah           True
amsterdam     False
dtype: bool


- A useful Series feature for many applications is that it automatically aligns by index label in arhtematic Operations  

In [91]:
print(obj3)

print(obj5)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
Ohio          35000.0
Texas         71000.0
california        NaN
Oregon        16000.0
Utah           5000.0
amsterdam         NaN
dtype: float64


In [94]:
obj3+obj5 # it added the values at the indexes 

Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah           10000.0
amsterdam          NaN
california         NaN
dtype: float64

- Both the Series object itself and its index have a name atttribute, which integrates with other areas of pandas functionality  

In [95]:
obj5.name="population"
obj5.index.name="States"

obj5

States
Ohio          35000.0
Texas         71000.0
california        NaN
Oregon        16000.0
Utah           5000.0
amsterdam         NaN
Name: population, dtype: float64

In [107]:
# A series's indexcan be altered in place by assignment 
print(obj)

obj.index=["A","B","C","D"]

0    4
1    7
2   -5
3    3
dtype: int64


In [108]:
obj

A    4
B    7
C   -5
D    3
dtype: int64

### Merging & Joining

In merging, you can merge two or more data frames to form a single data frame. You can also decide and filter the columns that you want to keep common

In [109]:
import pandas as pd 

df1=pd.DataFrame({"HPI":[80,90,70,60],"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])
df2=pd.DataFrame({"HPI":[80,90,70,60],"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2005,2006,2007,2008])

merged=pd.merge(df1,df2)

print(merged)

   HPI  INT_RATE  IND_GDP
0   80         2       50
1   90         1       45
2   70         2       45
3   60         3       67


As you can see above, the two data frames has merged into a single data frame. Now, you can also specify the column which you want to make common. For example, I want the “HPI” column to be common and for everything else, I want separate columns.

In [6]:
df1=pd.DataFrame({"HPI":[80,90,70,60],"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])
df2=pd.DataFrame({"HPI":[80,90,70,60],"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2005,2006,2007,2008])

merge=pd.merge(df1,df2,on="HPI")
merge

HPI  INT_RATE_x  IND_GDP_x  INT_RATE_y  IND_GDP_y
0   80           2         50           2         50
1   90           1         45           1         45
2   70           2         45           2         45
3   60           3         67           3         67

### JOIN()

 This is another convenient method to combine two differently indexed data frames into a single resultant data frame. This operation is quite similar to the “merge” operation that we saw before, The only difference is that the ‘joining’ operation will be on the “index” instead of the “columns”. 

In [5]:
df1=pd.DataFrame({"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])

df2=pd.DataFrame({"Low_tier_HPI":[50,45,67,34],"Unemployment":[1,3,5,6]},index=[2001,2003,2004,2004])

joined=df1.join(df2)
joined

INT_RATE  IND_GDP  Low_tier_HPI  Unemployment
2001         2       50          50.0           1.0
2002         1       45           NaN           NaN
2003         2       45          45.0           3.0
2004         3       67          67.0           5.0
2004         3       67          34.0           6.0

In [7]:
import pandas as pd

df1=pd.DataFrame({"HPI":[80,90,70,60],"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])
df2=pd.DataFrame({"H":[8,9,7,6],"INT":[20,10,20,30],"IND":[5,4,4,6]},index=[2005,2006,2007,2008])
print(df1)
print(df2)

      HPI  INT_RATE  IND_GDP
2001   80         2       50
2002   90         1       45
2003   70         2       45
2004   60         3       67
      H  INT  IND
2005  8   20    5
2006  9   10    4
2007  7   20    4
2008  6   30    6


In [10]:
J=df1.join(df2)  # making the index of df1 common thats why index of df2 are not shown and values are NAN 
J

HPI  INT_RATE  IND_GDP   H  INT  IND
2001   80         2       50 NaN  NaN  NaN
2002   90         1       45 NaN  NaN  NaN
2003   70         2       45 NaN  NaN  NaN
2004   60         3       67 NaN  NaN  NaN

In [11]:
C=df2.join(df1)
C

H  INT  IND  HPI  INT_RATE  IND_GDP
2005  8   20    5  NaN       NaN      NaN
2006  9   10    4  NaN       NaN      NaN
2007  7   20    4  NaN       NaN      NaN
2008  6   30    6  NaN       NaN      NaN

In [12]:
df1=pd.DataFrame({"HPI":[80,90,70,60],"INT_RATE":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])
df2=pd.DataFrame({"H":[8,9,7,6],"INT":[20,10,20,30],"IND":[5,4,4,6]},index=[2001,2002,2003,2004])
print(df1)
print(df2)

      HPI  INT_RATE  IND_GDP
2001   80         2       50
2002   90         1       45
2003   70         2       45
2004   60         3       67
      H  INT  IND
2001  8   20    5
2002  9   10    4
2003  7   20    4
2004  6   30    6


In [14]:
G=df1.join(df2)
G

HPI  INT_RATE  IND_GDP  H  INT  IND
2001   80         2       50  8   20    5
2002   90         1       45  9   10    4
2003   70         2       45  7   20    4
2004   60         3       67  6   30    6

### Concatenation 

This operation basically glues the dataframe together. You can select the dimension on which you want to concatenate. For that, just use pd.concat and pass in the list of dataframes to concatenate together.

In [17]:
df1=pd.DataFrame({"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])
df2=pd.DataFrame({"Low_Tier_HPI":[50,45,67,34],"Unemployment":[1,3,5,6]},index=[1999,2007,2009,2015])

concat=pd.concat([df1,df2],axis=1)
concat

Int_Rate  IND_GDP  Low_Tier_HPI  Unemployment
2001       2.0     50.0           NaN           NaN
2002       1.0     45.0           NaN           NaN
2003       2.0     45.0           NaN           NaN
2004       3.0     67.0           NaN           NaN
1999       NaN      NaN          50.0           1.0
2007       NaN      NaN          45.0           3.0
2009       NaN      NaN          67.0           5.0
2015       NaN      NaN          34.0           6.0

In [21]:
df1=pd.DataFrame({"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]},index=[2001,2002,2003,2004])
df2=pd.DataFrame({"Low_Tier_HPI":[50,45,67,34],"Unemployment":[1,3,5,6]},index=[1999,2007,2009,2015])

con=pd.concat([df1,df2],axis=0)
con

Int_Rate  IND_GDP  Low_Tier_HPI  Unemployment
2001       2.0     50.0           NaN           NaN
2002       1.0     45.0           NaN           NaN
2003       2.0     45.0           NaN           NaN
2004       3.0     67.0           NaN           NaN
1999       NaN      NaN          50.0           1.0
2007       NaN      NaN          45.0           3.0
2009       NaN      NaN          67.0           5.0
2015       NaN      NaN          34.0           6.0

- We'll understand how to Change the index values in data frame

In [30]:
df=pd.DataFrame({"day":[1,2,3,4],"Visitors":[200,100,230,300],"Bounce_Rate":[20,45,60,10]})
df

day  Visitors  Bounce_Rate
0    1       200           20
1    2       100           45
2    3       230           60
3    4       300           10

In [31]:
df.set_index("day",inplace=True)
df

Visitors  Bounce_Rate
day                       
1         200           20
2         100           45
3         230           60
4         300           10

In [32]:
df.index # inplace made the "day:

Index([1, 2, 3, 4], dtype='int64', name='day')

#### Changing the Column Headers 

- .rename()

In [19]:
import pandas as pd 

df=pd.DataFrame({"Day":[1,2,3,4],"Visitors":[200,100,230,300],"Bounce_Rate":[20,45,60,10]})

df

Day  Visitors  Bounce_Rate
0    1       200           20
1    2       100           45
2    3       230           60
3    4       300           10

In [20]:
df=df.rename(columns={"Visitors":"Users"})
df

Day  Users  Bounce_Rate
0    1    200           20
1    2    100           45
2    3    230           60
3    4    300           10

In [20]:
df.rename(columns=["Day":"week"])
df.rename(columns=("Day":"week"))

SyntaxError: invalid syntax (3929838173.py, line 1)

#### Data Munging

In data munging you convert a particular data into a different format. for example if you have a .csv file, you can convert it into .html you can convert it into any other data format as well

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Object Creation

s=pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
# Creating a DataFrame by passing a Numpy array with a datetime index and labeled columns

dates=pd.date_range("20240325",periods=6)

dates

DatetimeIndex(['2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28',
               '2024-03-29', '2024-03-30'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df

A         B         C         D
2024-03-25 -1.207563 -0.910162  0.376061  1.271094
2024-03-26  0.219707 -0.423473  1.815746  0.088323
2024-03-27 -0.103703 -1.183496 -0.908802 -0.067138
2024-03-28  1.144174  0.821661  0.265735  1.595604
2024-03-29  0.057251  0.272708  1.197501 -0.620189
2024-03-30  0.522444  0.395484  0.103330  1.135767

In [7]:
d=np.random.randn(6,2)  # random values in 6 rows 2 columns ie; 12 values
d

array([[-0.43536449, -0.86962565],
       [-2.32063613, -0.5327818 ],
       [-1.22970666, -1.31281751],
       [-1.58976368, -0.0248801 ],
       [ 2.6689722 ,  1.25310348],
       [ 0.33639741, -1.53372917]])

In [8]:
d=np.random.randn(6,2,5) # 6 
print(d)

[[[-1.16430647  1.31266279  0.99728235 -0.30590989 -1.19584425]
  [-0.41645554  0.25767124 -1.17729518 -0.51081283  0.58249197]]

 [[-0.54275898  0.78669609  0.61888361 -0.72724377 -1.52603862]
  [ 0.82871358 -0.88777272 -0.23822581  0.21518124 -0.95692947]]

 [[-1.1453705   0.11411696  0.1424876  -0.3544751  -1.14890847]
  [ 1.53831614 -1.63582453  1.44911186  0.40730189  1.79462891]]

 [[-0.39809468  1.23593085  0.77672684  0.6360078   0.11108463]
  [-0.88128302  0.20552681 -0.08430456 -0.34901035 -0.75778053]]

 [[-1.02539401 -0.42037232  0.30040713 -1.05876727 -0.55860666]
  [ 0.34202585  0.01794093 -0.04176909  0.77256823 -1.74912292]]

 [[ 1.22349597  0.30784874  1.04585556  2.0238508  -0.04858585]
  [-0.1319748  -0.12042199 -0.67511008  1.05054299  0.79966628]]]


#### Creating a dataFrame by passing a dictionary of objects that can be converted into a series-like structure 

In [9]:
df2=pd.DataFrame({"A":1.0,"B":pd.Timestamp("20240325"),"C":pd.Series(1,index=list(range(4)),dtype="float32"),
                 "D":np.array([3]*4,dtype="int32"),"E":pd.Categorical(["test","train","test","train"]),
                 "F":"foo"})
df2

A          B    C  D      E    F
0  1.0 2024-03-25  1.0  3   test  foo
1  1.0 2024-03-25  1.0  3  train  foo
2  1.0 2024-03-25  1.0  3   test  foo
3  1.0 2024-03-25  1.0  3  train  foo

In [10]:
# The columns of the resulting dataFrame have different dtype

df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

### Viewing Data

Here is how to view the top and bottom rows of the frame: 

In [11]:
df2.head(2)

A          B    C  D      E    F
0  1.0 2024-03-25  1.0  3   test  foo
1  1.0 2024-03-25  1.0  3  train  foo

In [12]:
df2.tail(2)

A          B    C  D      E    F
2  1.0 2024-03-25  1.0  3   test  foo
3  1.0 2024-03-25  1.0  3  train  foo

In [13]:
print(df2.index)
print(df2.columns)

Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


### Describe()

In [14]:
df.describe()
# shows a quick statistic summary of your data

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.105385 -0.171213  0.474929  0.567243
std    0.779225  0.792263  0.940876  0.885206
min   -1.207563 -1.183496 -0.908802 -0.620189
25%   -0.063464 -0.788489  0.143931 -0.028273
50%    0.138479 -0.075383  0.320898  0.612045
75%    0.446759  0.364790  0.992141  1.237262
max    1.144174  0.821661  1.815746  1.595604

### Transpose

In [15]:
df.T

2024-03-25  2024-03-26  2024-03-27  2024-03-28  2024-03-29  2024-03-30
A   -1.207563    0.219707   -0.103703    1.144174    0.057251    0.522444
B   -0.910162   -0.423473   -1.183496    0.821661    0.272708    0.395484
C    0.376061    1.815746   -0.908802    0.265735    1.197501    0.103330
D    1.271094    0.088323   -0.067138    1.595604   -0.620189    1.135767

### Sort

In [16]:
df

A         B         C         D
2024-03-25 -1.207563 -0.910162  0.376061  1.271094
2024-03-26  0.219707 -0.423473  1.815746  0.088323
2024-03-27 -0.103703 -1.183496 -0.908802 -0.067138
2024-03-28  1.144174  0.821661  0.265735  1.595604
2024-03-29  0.057251  0.272708  1.197501 -0.620189
2024-03-30  0.522444  0.395484  0.103330  1.135767

In [17]:
df.sort_index(axis=1,ascending=False)

D         C         B         A
2024-03-25  1.271094  0.376061 -0.910162 -1.207563
2024-03-26  0.088323  1.815746 -0.423473  0.219707
2024-03-27 -0.067138 -0.908802 -1.183496 -0.103703
2024-03-28  1.595604  0.265735  0.821661  1.144174
2024-03-29 -0.620189  1.197501  0.272708  0.057251
2024-03-30  1.135767  0.103330  0.395484  0.522444

In [18]:
df.sort_index(axis=0,ascending=False)

A         B         C         D
2024-03-30  0.522444  0.395484  0.103330  1.135767
2024-03-29  0.057251  0.272708  1.197501 -0.620189
2024-03-28  1.144174  0.821661  0.265735  1.595604
2024-03-27 -0.103703 -1.183496 -0.908802 -0.067138
2024-03-26  0.219707 -0.423473  1.815746  0.088323
2024-03-25 -1.207563 -0.910162  0.376061  1.271094

In [19]:
# Sorting by values 

df.sort_values(by="B")

A         B         C         D
2024-03-27 -0.103703 -1.183496 -0.908802 -0.067138
2024-03-25 -1.207563 -0.910162  0.376061  1.271094
2024-03-26  0.219707 -0.423473  1.815746  0.088323
2024-03-29  0.057251  0.272708  1.197501 -0.620189
2024-03-30  0.522444  0.395484  0.103330  1.135767
2024-03-28  1.144174  0.821661  0.265735  1.595604

### Getting

In [20]:
df["A"]

2024-03-25   -1.207563
2024-03-26    0.219707
2024-03-27   -0.103703
2024-03-28    1.144174
2024-03-29    0.057251
2024-03-30    0.522444
Freq: D, Name: A, dtype: float64

In [21]:
df[0:3]

A         B         C         D
2024-03-25 -1.207563 -0.910162  0.376061  1.271094
2024-03-26  0.219707 -0.423473  1.815746  0.088323
2024-03-27 -0.103703 -1.183496 -0.908802 -0.067138

In [23]:
df["20240325":"20240326"]

A         B         C         D
2024-03-25 -1.207563 -0.910162  0.376061  1.271094
2024-03-26  0.219707 -0.423473  1.815746  0.088323

In [24]:
# Selcting by label
# For granting a cross section using a label

df.loc[dates[0]]

A   -1.207563
B   -0.910162
C    0.376061
D    1.271094
Name: 2024-03-25 00:00:00, dtype: float64

In [25]:
# Selcting on a multi-axis by label

df.loc[:,["A","B"]]

A         B
2024-03-25 -1.207563 -0.910162
2024-03-26  0.219707 -0.423473
2024-03-27 -0.103703 -1.183496
2024-03-28  1.144174  0.821661
2024-03-29  0.057251  0.272708
2024-03-30  0.522444  0.395484

In [32]:
df.iloc[0:6,0:2]

A         B
2024-03-25 -1.207563 -0.910162
2024-03-26  0.219707 -0.423473
2024-03-27 -0.103703 -1.183496
2024-03-28  1.144174  0.821661
2024-03-29  0.057251  0.272708
2024-03-30  0.522444  0.395484

In [33]:
# Showing label sclicing both endpoints are included:

df.loc["20240325":"20240327",["A","B"]]

A         B
2024-03-25 -1.207563 -0.910162
2024-03-26  0.219707 -0.423473
2024-03-27 -0.103703 -1.183496

In [34]:
# Reduction in the dimensions of the returned object:

df.loc["20240325",["A","B"]]

A   -1.207563
B   -0.910162
Name: 2024-03-25 00:00:00, dtype: float64

In [35]:
# For gettinf a scalar values:

df.loc[dates[0],"A"]

-1.2075633165984407

In [36]:
# Selecting by position 

# selecting via the position of the passed integers 

df.iloc[3]

A    1.144174
B    0.821661
C    0.265735
D    1.595604
Name: 2024-03-28 00:00:00, dtype: float64

In [37]:
# for getting fast access to a scalar (equivalent to the prior method ):

df.at[dates[0],"A"]

-1.2075633165984407

In [38]:
# By integer slices, acting similar to NumpyPython

df.iloc[3:5,0:2]

A         B
2024-03-28  1.144174  0.821661
2024-03-29  0.057251  0.272708

In [39]:
# By lists of integer position locations, similar to the Numpy Pyhton style

df.iloc[[1,2,4],[0,2]]

A         C
2024-03-26  0.219707  1.815746
2024-03-27 -0.103703 -0.908802
2024-03-29  0.057251  1.197501

In [40]:
# for slicing rows explicitly:

df.iloc[1:3,:]

A         B         C         D
2024-03-26  0.219707 -0.423473  1.815746  0.088323
2024-03-27 -0.103703 -1.183496 -0.908802 -0.067138

In [41]:
# for slicing columns explicitly 

df.iloc[:,1:3]

B         C
2024-03-25 -0.910162  0.376061
2024-03-26 -0.423473  1.815746
2024-03-27 -1.183496 -0.908802
2024-03-28  0.821661  0.265735
2024-03-29  0.272708  1.197501
2024-03-30  0.395484  0.103330

In [42]:
# for getting a value explicitly 

df.iloc[1,1]

-0.42347289459661214

In [43]:
# for getting fast access to a scalar (equivalent to the prior method )

df.iat[1,1]

-0.42347289459661214

# Essential Fuctionalities

This section will walk you through the fundamental mechanics of ineracting with the data contained in a Series or DataFrame

### Reindexing 

An important method on pandas objects is reindex, which means to create a new object with the values rearranged to align with the new index.

In [1]:
import pandas as pd
import numpy as np 

In [2]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'],)
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2=obj.reindex(['a','b','c','d','e'])

obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3=obj.reindex(['x','y','z','v'])
obj3 
# from here we got to know that the .reindex can add new index or 
                                                  #rearrange the existing index but can't rename the existing index

x   NaN
y   NaN
z   NaN
v   NaN
dtype: float64

In [5]:
obj.reindex(['x','y','z','v'])

x   NaN
y   NaN
z   NaN
v   NaN
dtype: float64

In [6]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

 With DataFrame, reindex can alter the (row) index, columns , or both. When passed only a sequence, it reindexes the rows in the result

In [7]:
frame=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['Ohio','Texas','California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [8]:
frame2=frame.reindex(index=['a','b','c','d'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [9]:
# THe column can be reindexed wih the cokumns keyword 

states=['Texas','Utah','California']

frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

- Another way to reindex a particular axis is to pass the new axis labels as a positional argument and then specify the axis to reindex with the axis keyword 

In [10]:
frame.reindex(states,axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [11]:
frame.reindex(states,axis="index")

Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [12]:
frame.reindex(states,axis=1)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping entries from an Axis 

Droppping one or more entries from an axis is simple if you already have an index array or list without those entries, since you can use the reindex method or .loc-based indexing. As that can require a bit of munging and set logic, the drop mehod will return a new object with the indicated value or values deleted from an axis 



- Data munging, also known as data wrangling, is the process of converting raw data into a more usable format. Often,data munging ocurs as a precursor to data analytics or data integration. High-quality data is essential for sophisticated data operastions

In [2]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [3]:
new_obj= obj.drop('c')

new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [4]:
obj.drop('d','c')

TypeError: Series.drop() takes from 1 to 2 positional arguments but 3 were given

In [5]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [6]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

 With DataFrame,index values can be deleted from either axis 

In [8]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New York'],
                  columns=['one','two','three','four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [9]:
# Calling drop with a sequence of labels will drop values 

# from the row labels(axis=0)

data.drop(index=['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
# To drop labels from the columns, instead use the columns keywords:

data.drop(columns=['two'])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [11]:
# You ca also drop values fom the columns by passing axis=1(Which is like Numpy) or axis="columns"

data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [12]:
data.drop(['two','three'],axis='columns')

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

### Indexing, Seclecting and filtering 

Series indexing (obj[]) works analogously to Numpy array indexing,except you can use the Series index values instead of only integers

In [2]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [3]:
obj['b']

1.0

In [4]:
obj[1]

C:\Users\hplap\AppData\Local\Temp\ipykernel_10300\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [5]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [8]:
obj[['b','c','a']]

b    1.0
c    2.0
a    0.0
dtype: float64

In [9]:
obj[[1,3]]

C:\Users\hplap\AppData\Local\Temp\ipykernel_10300\1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [10]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

#### NOTE*

- It can be a common newbie error to try to call .loc or .iloc like function rather than"indexing into" with square brackets. The square bracket notation is used to enable slice operation and to allow for indexing on multiple axes with DataFrame objects

- Indexing into a DataFrame retrieves one or more columns either with a single value or sequence 

In [15]:
data= pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New York'],
                                        columns=['one','two','three','four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [16]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [17]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [21]:
# Both indexing function works with slices in addition to single labels or lists of labels:

data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [22]:
data.loc['Utah','two']

9

In [24]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [26]:
# Boolean arrays can be used with loc but not iloc:

data.loc[data.three>=3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [27]:
data.iloc[data.three>=3]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

#### Data Cleaning and Preparation

- During the course of doing data analysis and modeling, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging. Such tasks are often reported to take up 80% or more of an analyst's time. Sometimes the way that data is stored in files or databases is not in the right format for a particular task.

- Many researchers choose to do ad hoc processing of data from one form to another using a general-purpose programming language, like Python, Perl, R, or Java, or Unix text-processing tools like sed or awk. Fortunately, pandas, along with the built-in Python language features, provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.


#### Handling Missing Data

- Missing data occurs commonly in many data analysis applications. One of the goals of pandas is to make working with missing data as painless as possible. For example, all of the descriptive statistics on pandas objects exclude missing data by default.

- The way that missing data is represented in pandas objects is somewhat imperfect, but it is sufficient for most real-world use. For data with float64 dtype, pandas uses the floating-point value NaN (Not a Number) to represent missing data. pandas.isna Function: This function is used to detect missing values in an array-like object, DataFrame, or Series. Missing values can be represented as NaN (Not a Number), None, or NaT (Not a Time for datetime objects) in pandas. pandas.isna returns a boolean array of the same shape as the input, where each element indicates whether the corresponding value is missing (True) or not (False).

##### The Meaning:

- The statement emphasizes the convenience provided by functions like pandas.isna. When working with data, especially real-world data, dealing with missing values is a common challenge. Missing data can arise due to various reasons, such as errors in data collection, processing, or transmission.

- Abstract away many of the annoying details: This means that pandas.isna simplifies the process of identifying missing values in your data. Instead of writing complex and error-prone code to manually check for missing values, you can use this concise and efficient function. It "abstracts away" the underlying complexity, allowing you to focus on higher-level analysis tasks without getting bogged down by the details of handling missing data.

- We call this a sentinel value: when present, it indicates a missing (or null) value:


In [28]:
import numpy as np
import pandas as pd 

float_data= pd.Series([1.2,-3.5,np.nan,0])

float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [30]:
 # The isna method gives us a Boolean Series with true where values are null

float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [32]:
string_data=pd.Series(["aardvark",np.nan,None,"avocado"])

string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [34]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [38]:
float_d=pd.Series([1,2,None],dtype='float64')

float_d.isna()

0    False
1    False
2     True
dtype: bool

## Converting data frame into excel

In [2]:
import numpy as np
import pandas as pd 

In [5]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4'])
df

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [6]:
# name.to_csv('give name to csv file'.cs)

df.to_csv('savedata.csv')

### Data Frame and  Series 

In [16]:
print(df.loc['R1'])
type(df.loc['R1']) # this is series becuase it have only  one Row and multiple columns 
                # DataFrame should atleast consists of 2 row and 2 columns 

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32


pandas.core.series.Series

In [19]:
print(df.iloc[0:2,1])
type(df.iloc[0:2,1]) # it have 2 row but 1 column so it will be consider as Series 

R1    1
R2    5
Name: C2, dtype: int32


pandas.core.series.Series

In [18]:
print(df.iloc[0:2,0:2])
type(df.iloc[0:2,0:2])  # it is a dataframe cause it have 2 row and two columns 

    C1  C2
R1   0   1
R2   4   5


pandas.core.frame.DataFrame

### Convertiing DataFrame into arrays 

In [20]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
# Converitng some of the features and row to df into arrays 

df.iloc[1:3,2:3].values

array([[ 6],
       [10]])

In [25]:
# Value_count()

df['C1'].value_counts()

C1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [27]:
#Unique()

df['C2'].unique()

array([ 1,  5,  9, 13, 17])

In [28]:
df['C1']

R1     0
R2     4
R3     8
R4    12
R5    16
Name: C1, dtype: int32

In [29]:
df[['C1','C2']]

C1  C2
R1   0   1
R2   4   5
R3   8   9
R4  12  13
R5  16  17